### ISSUE TITLE
DICOM files not displaying

### ISSUE THREAD

**Issue by meself001** [JamesAPetts/ohif-viewer-XNAT-plugin#1]
Hi James,
We have some DICOM files from a study that upload fine into XNAT 1.7.4.1, with successful thumbnail generation, but the OHIF plugin (testing with v0.3.1) doesn't display anything. By comparison, the native XNAT viewer is able to display them.  Would you care to get a copy of the data set to help with your plugin's development? If so, I can make the zipped data (5.4 MB) available. I tried emailing you a URL for it to your address in the git commit logs, but that address bounces.
Mark

**Comment by JamesAPetts** [comment]
Dear @meself001 ,

Thank you for the message.

Sorry for the late reply, I've been rather busy. I would be most grateful if you are able to send the problem DICOMs and I'll have a look into it.

Here at the ICR we've been having trouble with some multi-frame DICOMs from PET/CT scanners, as can be seen in this issue submission: https://github.com/OHIF/Viewers/issues/174. I've had some private communication that this is being worked on.

If there are further formats that the viewer can't yet support I'll pass them on to the OHIF team, and if it turns out to be an issue with my own implementation I'll have a look at it!

My GitHub correspondence e-mail is jamespetts@gmail.com. For some reason it changed to be hidden recently, I have just made it public again.

Thanks,
James
