### ISSUE TITLE
Viewer cannot display scans with missing "UID" property

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#12]
The DICOM standard pretty clearly requires that (0020,000E) Series Instance UID be present and unique for all series. I'm not talking about that value being missing from the DICOM files themselves. Rather...

XNAT stores the Series Instance UID for incoming scans as a "UID" property on the scan object when being imported in a standard way (that will perform metadata extraction). However, this field is not at all required, so if:
- Somebody has a custom importer to insert the DICOM files that does not set this property, OR
- Data is imported through the REST API by creating resources manually and adding files, OR
- etc.
then this value may not be present. The viewer uses this field, and doesn't recover when it's not present. Attempting to view a scan without the "UID" property results in something like this:
<img width="1341" alt="screen shot 2019-01-09 at 11 46 05 am" src="https://user-images.githubusercontent.com/7414724/50918433-d60bcb80-1405-11e9-9eac-fc570b26bf3e.png">

Note: the easiest way to recreate the issue is to just:
1. Take a normal session that works in the viewer.
2. Click Download > Download XML
3. Find one of the scan objects in the XML, and delete the "UID" field.
4. Reupload the XML via Upload > XML, with data deletion on.
5. The scan now should have its UID missing.
6. Delete the cached session JSON.
7. Load the viewer.

**Comment by JamesAPetts** [comment]
Right, so this happens because we use EtherJ (@JamesDarcy616 's library) to hoover up all the session info server side.

When we construct the URLs, we first generate a map from `seriesInstanceUID` to XNAT `ScanID` using the XML metadata, so that by just looking at the DICOM image we can construct the GET request URL which contains the appropriate scanID. I know JamesD's backend code for the ROI XNAT plugin does something similar.

The relevant lines are [here](https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/afbe37e6713d473eb214c7c7300e43be88e32daf/src/main/java/org/nrg/xnatx/ohifviewer/inputcreator/CreateExperimentMetadata.java#L163) and [here](https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/afbe37e6713d473eb214c7c7300e43be88e32daf/src/main/java/org/nrg/xnatx/ohifviewer/inputcreator/CreateOhifViewerMetadata.java#L139).

Is there an easier way to get the scanID of a scan, given the seriesInstanceUID?

**Comment by JamesAPetts** [comment]
As this repo is being deprecated and moved to Bitbucket, I'm closing this issue, feel free to bring it back up in the XNAT Development slack.
