### ISSUE TITLE
Snapshot feature seems to be missing?

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#20]
<img width="1119" alt="screen shot 2019-01-14 at 2 53 54 pm" src="https://user-images.githubusercontent.com/7414724/51140573-78fc8500-180c-11e9-95a7-3f0b9a18b141.png">

The help menu lists exporting of a snapshot with the annotations with this camera-like icon. I could just be missing it, but I've looked through the UI a lot, and I can't find it anywhere. It should probably either (*mutually exclusive*):
1. be removed from the help menu.
2. added to the UI (if it's actually there somewhere, and I'm just being obtuse, it should probably be explained how to access the feature in the help menu too).

**Comment by JamesAPetts** [comment]
Hey,

I recently turned this off since its not yet working in the cornerstoneTools v3. I'd like to point out we've been working on a separate proprietary branch mostly i.e. 1.9. So this 1.8 branch is a little state of disarray.

We'll work towards a stable/clear version for initial release though, so bare with me on silly things like this!

**Comment by JamesAPetts** [comment]
Removed from 1.8 branch.
