### ISSUE TITLE
Long Series Descriptions cause display issues in series list

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#22]
<img width="272" alt="screen shot 2019-01-15 at 9 43 37 am" src="https://user-images.githubusercontent.com/7414724/51195649-24f8ab80-18b3-11e9-8073-ec77f819e93c.png">

<img width="264" alt="screen shot 2019-01-15 at 9 38 28 am" src="https://user-images.githubusercontent.com/7414724/51195663-2c1fb980-18b3-11e9-88ce-2de2da02ffe9.png">

**Note:** these were not contrived examples I cooked up. These were some actual series descriptions I found on TCIA.

**Note 2:** `(0008,1030E) Series Description` has a VR of `LO`, which has a maximum length of **64 characters**. As such, series descriptions this long (or even significantly longer) are valid per the spec.

In cases like this, different unfortunate things can happen to the series number or frame counts. One example shows the numbers being cut-off in the middle (and these are only **single digit** numbers). The other example shows the numbers being replaced with ellipses entirely.

**Comment by JamesAPetts** [comment]
Hey @cmoore01 , could you post this (and maybe #23 bundled) onto the OHIF repo issues page? This is a more fundamental viewer issue, rather than XNAT-specific.

**Comment by JamesAPetts** [comment]
Hey @cmoore01, I've tidied up the UI for our version for now at least, I think this won't go OHIF core (if they want it) until the next version due to priorities in the core development.

I've modified the UI so that in the absolute worst case scenario everything shows, but more _typical_ combinations of series number and scan ID don't look too bare and ugly. It will wrap cleanly on spaces where they exist, or else wrap as needed if the description is all one word, or e.g. two 32 character words, etc.

![Screen Shot 2019-04-11 at 17 14 05](https://user-images.githubusercontent.com/25818497/55973362-4c2a0380-5c7d-11e9-8978-081fd89301e0.png)

I'll include this in the next update.
